# Generated by Django 4.0.3 on 2022-03-29 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicemodel',
            name='data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
