# Generated by Django 4.0.3 on 2022-03-29 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_alter_devicemodel_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devicecategorymodel',
            options={'ordering': ('-created_at',), 'verbose_name_plural': 'Device Categories'},
        ),
        migrations.AlterModelOptions(
            name='devicehistorymodel',
            options={'ordering': ('-created_at',), 'verbose_name_plural': 'Device Histories'},
        ),
        migrations.AlterModelOptions(
            name='devicemodel',
            options={'ordering': ('-created_at',), 'verbose_name_plural': 'Devices'},
        ),
        migrations.AddField(
            model_name='devicemodel',
            name='is_sensor',
            field=models.BooleanField(default=False),
        ),
    ]
