# Generated by Django 4.0.3 on 2022-03-30 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_alter_devicecategorymodel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicemodel',
            name='slug',
            field=models.SlugField(default='slug', max_length=255),
            preserve_default=False,
        ),
    ]
