# Generated by Django 4.0.3 on 2022-03-30 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_devicemodel_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicemodel',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
