# Generated by Django 4.0.3 on 2022-03-31 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0005_alter_devicemodel_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicecategorymodel',
            name='name',
        ),
        migrations.AddField(
            model_name='devicecategorymodel',
            name='icon_name',
            field=models.CharField(default='default-icon', max_length=50),
        ),
    ]
